### ISSUE TITLE
uninitialized constant Rack::Throttle::Limiter (NameError)

### ISSUE THREAD

**Issue by gchandramoulireddy** [dryruby/rack-throttle#38]
gem 'rack-throttle', '~> 0.4.2'

when i run i am getting this error, can you please provide solution for this

/data/public-api-internal/releases/20170303-002420-d4e212ca/vendor/bundle/ruby/2.2.0/gems/rack-throttle-0.4.2/lib/rack/throttle/time_window.rb:3:in `<module:Throttle>': uninitialized constant Rack::Throttle::Limiter (NameError)
from /data/public-api-internal/releases/20170303-002420-d4e212ca/vendor/bundle/ruby/2.2.0/gems/rack-throttle-0.4.2/lib/rack/throttle/time_window.rb:1:in `<module:Rack>'
from /data/public-api-internal/releases/20170303-002420-d4e212ca/vendor/bundle/ruby/2.2.0/gems/rack-throttle-0.4.2/lib/rack/throttle/time_window.rb:1:in `<top (required)>'
from /data/public-api-internal/releases/20170303-002420-d4e212ca/vendor/bundle/ruby/2.2.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require'
from /data/public-api-internal/releases/20170303-002420-d4e212ca/vendor/bundle/ruby/2.2.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require_with_backports'
from /data/public-api-internal/releases/20170303-002420-d4e212ca/lib/app/rate_limiter/request_throttle.rb:1:in `<top (required)>'
from /data/public-api-internal/releases/20170303-002420-d4e212ca/vendor/bundle/ruby/2.2.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require'
from /data/public-api-internal/releases/20170303-002420-d4e212ca/vendor/bundle/ruby/2.2.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require_with_backports'
from config.ru:11:in `block in <main>'
from /data/public-api-internal/releases/20170303-002420-d4e212ca/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
from /data/public-api-internal/releases/20170303-002420-d4e212ca/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
from config.ru:1:in `new'
from config.ru:1:in `<main>'
from /data/public-api-internal/releases/20170303-002420-d4e212ca/vendor/bundle/ruby/2.2.0/gems/unicorn-4.6.3/lib/unicorn.rb:48:in `eval'
from /data/public-api-internal/releases/20170303-002420-d4e212ca/vendor/bundle/ruby/2.2.0/gems/unicorn-4.6.3/lib/unicorn.rb:48:in `block in builder'
from /data/public-api-internal/releases/20170303-002420-d4e212ca/vendor/bundle/ruby/2.2.0/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:722:in `call'
from /data/public-api-internal/releases/20170303-002420-d4e212ca/vendor/bundle/ruby/2.2.0/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:722:in `build_app!'
from /data/public-api-internal/releases/20170303-002420-d4e212ca/vendor/bundle/ruby/2.2.0/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:140:in `start'
from /data/public-api-internal/releases/20170303-002420-d4e212ca/vendor/bundle/ruby/2.2.0/gems/unicorn-4.6.3/bin/unicorn:126:in `<top (required)>'
from /data/public-api-internal/releases/20170303-002420-d4e212ca/vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `load'
from /data/public-api-internal/releases/20170303-002420-d4e212ca/vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `<main>'

**Comment by FreekingDean** [comment]
Are you requiring it anywhere: `require 'rack/throttle'` ?
